use Test_WME

CREATE TABLE #Input (Nr NVARCHAR(MAX));

BULK INSERT #Input
FROM 'C:\Source\AdventOfCode\2020\input1.txt'
WITH (ROWTERMINATOR = '0x0A');

SELECT * FROM #Input

SELECT *, CAST(T1.Nr AS BIGINT) + CAST(T2.Nr AS BIGINT), CAST(T1.Nr AS BIGINT) * CAST(T2.Nr AS BIGINT)
FROM #Input T1
CROSS APPLY #Input T2
ORDER BY 3


--1472	548	2020	806656 is correct for part 1

SELECT *, CAST(T1.Nr AS BIGINT) + CAST(T2.Nr AS BIGINT) + CAST(T3.Nr AS BIGINT), CAST(T1.Nr AS BIGINT) * CAST(T2.Nr AS BIGINT) * CAST(T3.Nr AS BIGINT)
FROM #Input T1
CROSS APPLY #Input T2
CROSS APPLY #Input T3
ORDER BY 4

--893	320	807	2020	230608320 is correct for part 2


DROP TABLE #Input